// Memory data. Coordinates are in % of the map canvas (0-100).
// Replace `text` with real memories — placeholders shown clearly.

const PLACEHOLDER = '<span class="placeholder">[ Add the full memory here — what happened, how it felt, the small details that made it stick. ]</span>';

const SCOTT_MEMORIES = [
  { id: 'fathers-day', illus: 'tie', title: "Happy Father's Day", date: 'June 1992', x: 26, y: 14,
    text: `Father's Day, 1992. I was six years old, fresh out of first grade, and I knew what the gift was.\n\nWe were getting you a tie. I had been told, explicitly, not to say a word.\n\nWe were sitting in church when I turned to you and said: "I'll give you a hint. You're wearing one right now."\n\nThe moment it came out I knew I'd spoiled it. I was probably staring right at your tie when I said it. You gave me a smile.` },
  { id: 'boulder-lake', illus: 'mountain', title: 'Boulder Lake', date: 'Summer 2001', x: 72, y: 22,
    text: `The summer I turned fifteen, you drove us up into the Idaho mountains with nothing but packs and time.\n\nBoulder Lake is hard to reach. The trail felt like it went straight uphill the whole way. But when we got there, the water was crystal clear, the kind of clear where you can see everything. We made camp right on the bank.\n\nSomewhere in those evenings, you said it quietly: "Your Grandpa is getting pretty tired." I think I knew he was sick, but that was the moment I understood how serious it was. You said it the way you said most things. Simply, without drama. Looking back, I think you needed to be out there as much as I did. Maybe more.\n\nOn the drive up we'd stopped for a hitchhiker, a young guy who'd been kayaking the river and needed a lift. You didn't even hesitate. It felt like exactly the kind of thing you would do, and I remember noticing it.\n\nGrandpa didn't make it to the end of that summer. But I have that lake. I have those evenings. I have you telling me something hard in the kindest way you knew how.` },
  { id: 'bogus-basin', illus: 'ski', title: 'Skiing', date: 'Winter of 2002', x: 84, y: 32,
    text: `You and Mom gave Carter and me something we didn't fully understand at the time: two winters at Bogus Basin, at least twice a week, every week. Season passes. Gear. All of it.\n\nI know it was a sacrifice. The passes, the equipment. It adds up fast. But you found ways to make it work, used gear and whatever else it took, because you wanted us up on that mountain.\n\nAnd we were. All of us: you, Mom, Carter, me, and whatever friends we could drag along. We'd pack food and eat in the lodge between runs, days and nights on the snow together.\n\nLooking back, I think you knew something. That Carter and I were getting older, that the years at home were running short, and that you wanted to give us something we'd carry with us. You were right. I still carry it.` },
  { id: 'driving', illus: 'police', title: 'Back in the Saddle', date: 'March 2003', x: 14, y: 42,
    text: `You came right down to the high school parking lot. I'd pulled out without seeing the other car. A stupid mistake, and a minor one thankfully. No injuries, barely a scratch on anyone. The police came anyway. I got a ticket.\n\nWhat I remember most is you calmly pulling the front bumper the rest of the way off so we could drive the car home. You weren't angry. Just glad I was okay. I think you knew I'd learned my lesson in the best possible way: scared enough to remember it, with nobody actually hurt.\n\nI was sure I was done driving for months. But that weekend we drove down to Salt Lake for general conference, and you put me behind the wheel for most of it. I remember being terrified just to turn left out of the neighborhood onto Eagle Road. You knew I needed to get back in the saddle before the fear had time to settle in.\n\nThere was the ticket, and the deductible, and the debt I owed you. But I noticed the ways you quietly found to knock a little off what I owed, here and there. I felt grateful then. I feel it now. Grateful to have you on my side.` },
  { id: 'steak', illus: 'steak', title: 'Steak Dinner the Night Before', date: 'Match-night ritual', x: 52, y: 50,
    text: `The night before every match, Dad made the steak. Same plate, same pep talk.\n\n${PLACEHOLDER}` },
  { id: 'bsu', illus: 'football', title: 'Saturdays on the Blue', date: 'BSU football, every fall', x: 80, y: 60,
    text: `Saturdays in the fall meant one thing — Broncos on the blue, Dad on the couch beside me.\n\n${PLACEHOLDER}` },
  { id: 'trivia', illus: 'boardgame', title: 'Trivial Pursuit Champion', date: 'Family game nights', x: 30, y: 68,
    text: `He knew every answer. Every. Single. One.\n\n${PLACEHOLDER}` },
  { id: 'drum', illus: 'drum', title: 'Watching Dad Drum', date: 'Anytime he sat down at the kit', x: 76, y: 74,
    text: `There was a different version of Dad behind the kit. Lighter. All rhythm.\n\n${PLACEHOLDER}` },
  { id: 'flyfish', illus: 'flyfish', title: 'Warm Lake', date: 'Summer 2025', x: 24, y: 82,
    text: `As told by Chandler. \n\nGrandpa took us to a cabin at Warm Lake. It was a small cabin. Two bedrooms and a bathroom and a kitchen, and no TV. That was okay though.\n\nOn the way there we saw deer out the window.\n\nThe best thing we did was fishing. I caught the first fish every single day! We caught a lot of them, and then we ate them. Grandpa taught me how to catch fish. When I caught one I got to hold it and it was moving all around in my hands.\n\nMy favorite meal on the whole trip was pancakes at a restaurant.\n\nAt night we read books in our beds to settle down before sleeping.\n\nIf I could go back, I would want to get a Twinkie from the store.\n\nMy favorite thing about Grandpa is fishing.` },
  { id: 'mission', illus: 'roadtrip', title: 'The Drive to College', date: 'After my mission', x: 68, y: 88,
    text: `Just the two of us, the open road, and a trunk full of dorm-room boxes.\n\n${PLACEHOLDER}` },
];

const CARTER_MEMORIES = [
  { id: 'c-sawtooth', illus: 'mountain', title: 'Fifty Miles in the Sawtooths', date: 'My first fifty-miler', x: 22, y: 18,
    text: `The first fifty mile hike tested me in ways I wasn't fully prepared for, both physically and mentally. The thing I remember most is overnight preparing for bed and getting into the tent with you. I was right on the cusp of being old enough to go so I know everyone was worried about me, but I had all the support I needed.\n\nI protested sleeping on a pad, still you brought one for me to sleep on. I probably resisted brushing my teeth, washing my face, all the things a wiser and more seasoned hiker has learned to do, but still you helped me through it with patience. On the trail I'm sure I was distracted by friends and wild boy antics, but in the memories that still linger about those moments it's your presence that is most strongly felt.\n\nThank you for looking out for me, for trying to teach me when I didn't want to be taught, for putting in effort, and for letting me enjoy nature in the most raw and powerful way.` },

  { id: 'c-park-city', illus: 'flyfish', title: 'Important words for a son in need', date: 'September 29, 2014', x: 62, y: 22,
    text: `SEPT 29th 2014:\n\nMy dad was in town this last few days.  He had a work meeting in park city and then came thursday down to hang out with me and fish.\n\nhe is obsessed with fishing right now but i feel like its good for him.  But as he was leaving he said something that had a profound impact on me.  It was very simple but i was deeply moved.  As he was leaving he asked to have a word of prayer.  I said a prayer and then he hugged me and said “i love you son.  You are a good man.  You really are, and i know you try your best to be one.  I’m proud of you, don’t let the little frustrations of life get you down.  It will all work out, just hang in there.”\n\nJust hearing my dad say i was a good man.  It was powerful.  Because i really do try to be a good man, and i mess up a lot.  But the validation of a father, that meant a lot.  And i knew he was moved to say that, because i needed to hear that.  God puts people around us that we need around us.  Perhaps sometimes they need us around them.  I want to express my gratitude for my father and for his goodness.  I’m grateful i have a worthy father who has the spirit with him.  He is a great man.` },

  { id: 'c-trivia', illus: 'boardgame', title: 'Trivial Pursuit', date: 'Sunday evenings, Hobble Creek', x: 84, y: 32,
    text: `One of our favorite Sunday evening pastimes growing up in the Hobble Creek house. Scott and Dad vs. Mom and Carter usually — which maybe didn't make the most sense from a competitive perspective, but I never shied away from the challenge.\n\nWe enjoyed those moments of intellectual warfare, and I was always impressed by your depth of knowledge of so many subjects (Scott's too in fact). I think deep down I knew I couldn't compete on that level especially at that age, but you instilled in me the importance of knowledge and intellect. I aspired to be like you were in that game — able to call upon your past experience and regurgitate a random factoid.` },

  { id: 'c-fhe', illus: 'church', title: 'Family Home Evening', date: 'Monday nights', x: 14, y: 38,
    text: `This is something I only appreciate now that I have 3 kids of my own. How challenging it is to carve out sacred time on a consistent basis to learn and grow with each other, to step out of the busy-ness of the day or week and to think about godly things.\n\nYou always made sure we did this (and Mom as well). You shared in those moments so many precious bits of wisdom that stuck with me, but by far the most profound bit — making the time and space to be in those moments together.\n\nI try and fail to do things like this now that I'm a dad. I'll continue to try, but I have incredible respect now for the consistency and intention with which you brought our family together. THANK YOU.` },

  { id: 'c-jam', illus: 'car', title: 'Helping Me Out of a Jam', date: '2 a.m., after a tournament', x: 50, y: 46,
    text: `It's 2 a.m. in the middle of winter and I've just returned home from a wrestling tournament in Idaho Falls. We arrive at Centennial High School and get off the charter bus. Chance Hyer and I jump in my Suzuki Esteem and I start heading toward his house.\n\nThe past few days have been snowy and the road is frozen over in some places, although for my young eyes I'm not as attuned to the conditions as I should be. I make the final turn into his cul-de-sac but I've got too much speed and we hit a patch of ice. I'm headed right toward the hard curb. BANG.\n\nThe way the wheel hit the curb it snapped the axle and the car was out of commission. Luckily for Chance we had arrived at his house, unlucky for me my car wasn't going to get me home. We ran into Chance's house and I called you. 2 a.m. middle of the night you answer, I tell you with some shame that I'm going to need you to pick me up. You tell me to call the tow company to get the car to the shop at Fairly's. A few minutes later you're there to pick me up.\n\nI don't remember the conversation on the ride home to be honest. I'm sure there was some talk about being able to prevent these type of incidents in the future, but what is important looking back is that you were there, and that I always knew you would be there. There were no doubts in my mind that if I was in a jam and needed help, you would answer the call.` },

  { id: 'c-fajitas', illus: 'steak', title: 'The Best Meal Ever?', date: 'After my mission, on the way to Provo', x: 80, y: 52,
    text: `The best fajitas I've ever eaten in my life were at an Applebee's in Rexburg, Idaho — who would have thought.\n\nIt had been a long day. You and I drove all day in an old truck, I want to say with a trailer. We're going to help Scott and Natasha move into their new apartment in Rexburg because they had just gotten married. We spent the freezing cold night moving couches and boxes and after we had thoroughly exhausted ourselves we looked for any open eating establishment we could find.\n\nIt just so happened to be Applebee's. We both looked at the menu and almost simultaneously pointed to the fajitas — "those look pretty good right now." Those bad boys came out of the kitchen with all the usual fanfare, sizzles and splatters all the way down into our starving gullets. What a meal! What a great time to spend with each other.\n\nWe then stayed in a motel of some sort and continued our journey to Provo to drop me off at college for my first semester back from my mission.` },

  { id: 'c-robie', illus: 'running', title: 'Running Robie', date: 'Add a date', x: 24, y: 60,
    text: `${PLACEHOLDER}` },

  { id: 'c-wrestling', illus: 'wrestle', title: 'Wrestling', date: 'Add a date', x: 56, y: 68,
    text: `${PLACEHOLDER}` },

  { id: 'c-grandparents', illus: 'home', title: "Sundays at Grandma & Grandpa Hurst's", date: 'Sunday afternoons', x: 22, y: 80,
    text: `${PLACEHOLDER}` },

  { id: 'c-moab', illus: 'bike', title: 'Moab — Beaver Ridge to Onion Creek', date: 'Add a date', x: 70, y: 84,
    text: `${PLACEHOLDER}` },
];

window.MEMORIES = { scott: SCOTT_MEMORIES, carter: CARTER_MEMORIES };
